
COMPONENT_ADD_LDFLAGS := $(COMPONENT_PATH)/../../libLOKAV2.a

ULP_EXPORTS_LD := $(COMPONENT_PATH)/ulp/ulp_service.ld

COMPONENT_ADD_LDFLAGS := -l$(COMPONENT_NAME) -T $(ULP_EXPORTS_LD)
COMPONENT_EXTRA_INCLUDES := $(COMPONENT_BUILD_DIR)